export const elements = {
  photoTab: document.querySelector('#photoTab'),
  liveTab: document.querySelector('#liveTab'),
  photoView: document.querySelector('#photoView'),
  liveView: document.querySelector('#liveView'),
  imageInput: document.querySelector('#imageInput'),
  predictButton: document.querySelector('#predictButton'),
  photoStatus: document.querySelector('#photoStatus'),
  photoPreview: document.querySelector('#photoPreview'),
  photoOverlay: document.querySelector('#photoOverlay'),
  photoDetections: document.querySelector('#photoDetections'),
  photoCountBadge: document.querySelector('#photoCountBadge'),
  cameraSelect: document.querySelector('#cameraSelect'),
  refreshButton: document.querySelector('#refreshButton'),
  streamButton: document.querySelector('#streamButton'),
  liveStatus: document.querySelector('#liveStatus'),
  livePreview: document.querySelector('#livePreview'),
  liveOverlay: document.querySelector('#liveOverlay'),
  liveDetections: document.querySelector('#liveDetections'),
  liveCountBadge: document.querySelector('#liveCountBadge'),
};
